#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


rm -rf 0 > /dev/null 2>&1

cleanCase

rm -f `find . -name "*.obj"` > /dev/null 2>&1
rm -f `find . -name "cell*"` > /dev/null 2>&1
rm -f inner.stl
