#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir 0 > /dev/null 2>&1

runApplication blockMesh
runApplication topoSet
runApplication subsetMesh fluidSource -overwrite
runApplication createPatch -overwrite

rm -rf 0
cp -r 0.org 0

runApplication setFields
runApplication interFoam
