#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

./Allclean.2D

./Allclean.3D

(
    rm -rf post/results

    cd post/latex && rm `ls | grep -v tex` -f > /dev/null 2>&1
)

rm -f `find . -name *.obj` > /dev/null 2>&1
rm -f `find . -name cell*` > /dev/null 2>&1
