/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

/* not implemented...
 * still!

inline Foam::coupledPolyPatch::transformType
Foam::bellerophonPolyPatch::transform() const
{
    Info<< "bellerophonPolyPatch::transform()"
        << " at bellerophonPolyPatchI.H:48" << nl << endl;

    return transform_;
}


inline const Foam::vector& Foam::bellerophonPolyPatch::rotationAxis() const
{
    Info<< "bellerophonPolyPatch::rotationAxis()"
        << " at bellerophonPolyPatchI.H:58" << nl << endl;

    return rotationAxis_;
}


inline const Foam::point& Foam::bellerophonPolyPatch::rotationCentre() const
{
    Info<< "bellerophonPolyPatch::rotationCentre()"
        << " at bellerophonPolyPatchI.H:67" << nl << endl;

    return rotationCentre_;
}


inline const Foam::vector& Foam::bellerophonPolyPatch::separationVector() const
{
    Info<< "bellerophonPolyPatch::separationVector()"
        << " at bellerophonPolyPatchI.H:76" << nl << endl;

    return separationVector_;
}
*/

// ************************************************************************* //
