#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

(
    cd backgroundMesh
    cleanCase
)

(
    cd wingMesh
    cleanCase
    rm -f inner.stl
)

rm -rf [0-9]*deg
rm -rf post/results
(
    cd post/latex && ls | grep -v -e ".*\.tex$" | xargs rm -f && echo "Cleaning latex"
)
