#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


(
    cd steady/overset
    cleanCase
    rm -rf donorFaceLinks_*
)

(
    cd steady/single
    cleanCase
    rm -rf donorFaceLinks_*
)

(
    cd transient/overset
    cleanCase
    rm -rf donorFaceLinks_*
)

(
    cd transient/single
    cleanCase
    rm -rf donorFaceLinks_*
)

rm -f `find . -name cell*` > /dev/null 2>&1
