#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


(
    cd steady/overset

    runApplication blockMesh
    runApplication diffusiveFoam
)

(
    cd steady/single

    runApplication blockMesh
    runApplication diffusiveFoam
)

#(
#    cd steady/overset
#
#    runApplication blockMesh
#    runApplication diffusiveFoam
#)
#
#(
#    cd steady/overset
#
#    runApplication blockMesh
#    runApplication diffusiveFoam
#)


# create some report here!
