#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0

python createDicts.py

runApplication decomposePar
runParallel pimpleDyMFoam 4
runApplication reconstructPar
