#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh
runApplication surfaceMeshTriangulate -patches "(inner)" inner.stl
runApplication holeCutter
runApplication subsetMesh -overwrite liveCells

