#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

(
    cd overset
    cleanCase
)

(
    cd single
    cleanCase
)

rm -rf post/results
(
    cd post/latex
    ls | grep -v tex | xargs rm -f
)
