#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

(
    cd overset
    runApplication blockMesh
    runApplication simpleDyMFoam
)

(
    cd single
    runApplication blockMesh
    runApplication simpleFoam
)

# create some report here!
(
    mkdir post/results
    cd post/scripts
    ./postProcessing
    cd ../latex
    latex validation.tex
    dvips validation.dvi
    ps2pdf validation.ps
    latex validation.tex
    dvips validation.dvi
    ps2pdf validation.ps
    latex validation.tex
    dvips validation.dvi
    ps2pdf validation.ps
    rm *.ps *.aux *.dvi *.log
)
