#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


(
    cd 2d
    cleanCase
    rm -rf constant/polyMesh/* 0
)

(
    cd 3d
    cleanCase
    rm -rf system/extrudeMeshDict* 0
)

